reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.10
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik/certs:/etc/traefik/certs
    - ./traefik:/etc/traefik
    ports:
    - 80:80
    - 443:443
    - 7777:8080
    restart: always
    networks:
    - traefik-proxy

